name: Percy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  percy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
      - run: yarn install
      - run: yarn build
      - run: yarn ci
        env:
          PERCY_TOKEN: "${{ secrets.PERCY_TOKEN }}"
